### ISSUE TITLE
Consider releasing a new version

### ISSUE THREAD

**Issue by matkoniecz** [djberg96/sys-filesystem#44]
warning: rb_safe_level will be removed in Ruby 3.0

> sys-filesystem-1.3.4/lib/sys/unix/sys/filesystem.rb:204: warning: rb_safe_level will be removed in Ruby 3.0

https://github.com/djberg96/sys-filesystem/blob/ffi/lib/sys/unix/sys/filesystem.rb#L204 indicates that it is fixed but not released as 1.3.4 is latest and current version - https://github.com/djberg96/sys-filesystem/blob/ffi/sys-filesystem.gemspec#L5

**Comment by djberg96** [comment]
The windows tests are busted atm, I need to make sure that change works as intended.

**Comment by djberg96** [comment]
Ok, basically the issue is that you can't stat a regular file on Windows, it must be a directory, so we can't stat a `File` object either. I used to know that, but had forgotten.

If you want the nitty gritty reasons, it's because under the hood Ruby uses the Windows `CreateFile` function, which cannot open a directory path. Not without a special flag, anyway. You can see this in practice like so:

`File.open("C:/") # => Errno::EISDIR`

Anyway, I'm porting all the tests over to rspec, and updating the docs for the Windows version.

**Comment by djberg96** [comment]
I've released 1.4.0 this morning. :)
