### ISSUE TITLE
missing files system type -- @base_type is empty

### ISSUE THREAD

**Issue by jablin** [djberg96/sys-filesystem#64]
On a RHEL7.9 with ruby 2.6.5:

    $ ruby -r sys-filesystem -e 'ARGV.each { |path| pp Sys::Filesystem.stat(path).base_type }' / /dev /proc /sys
    ""
    ""
    ""
    ""

I would have expected: "xfs", "devtmpfs", "proc" and "sysfs"

**Comment by djberg96** [comment]
Under the hood this library uses the `statvfs` function for the `Filesystem.stat` method because POSIX. The `base_type` property is only defined if the underlying struct defines an `f_basetype` struct member. So far as I know only Solaris does.

https://man7.org/linux/man-pages/man3/statvfs.3.html

You can get that information using the Filesystem.mounts method, however.

Maybe I should just switch the Linux code to use statfs for a stat call?

**Comment by djberg96** [comment]
Update: some more info here: https://stackoverflow.com/questions/1653163/difference-between-statvfs-and-statfs-system-calls

**Comment by djberg96** [comment]
I looked into implementing this on Linux, only to discover that the constants in the magic.h file is not a reliable way to determine the filesystem type:

https://stackoverflow.com/questions/17485221/what-kind-of-macro-correspond-to-what-kind-of-file-system-in-linux

And I've no idea how to distinguish between ext2/3/4 since they use the same magic number. The general answer seems to be to use mount information, which you can already do with the `mounts` method, so that's how you'll have to do it.
